= Atlanmod Commons

image:https://travis-ci.org/atlanmod/Commons.svg?branch=master[Build Status,link=https://travis-ci.org/atlanmod/Commons]
image:https://maven-badges.herokuapp.com/maven-central/org.atlanmod.commons/commons-core/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/org.atlanmod.commons/commons-core]
image:https://codecov.io/gh/atlanmod/Commons/branch/master/graph/badge.svg[CodeCov,link=https://codecov.io/gh/atlanmod/Commons/branch/master]
image:https://api.codacy.com/project/badge/Grade/d5df667a5b264f9e95ad0095719b7d6a[Codacy,link=https://www.codacy.com/app/atlanmod/Commons?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=atlanmod/Commons&amp;utm_campaign=Badge_Grade]
image:https://img.shields.io/badge/javadoc--blue.svg[Javadoc,link=https://atlanmod.github.io/Commons/releases/latest/doc/]
image:https://img.shields.io/badge/licence-EPL--2.0-blue.svg[Licence,link=https://www.eclipse.org/legal/epl-2.0/]
image:https://www.javadoc.io/badge/org.atlanmod.commons/commons-core.svg[Javadocs,link=https://www.javadoc.io/doc/org.atlanmod.commons/commons-core]

This library is a set of common classes and methods, including:
- Lazy objects and references for on-demand loading, and local caching
- An asynchronous logger
- A wrapper for caching, using https://github.com/ben-manes/caffeine[Caffeine]
- A wrapper for hashing, using https://github.com/OpenHFT/Zero-Allocation-Hashing[Zero-allocation Hashing]
- A wrapper for serialization, using https://github.com/RuedigerMoeller/fast-serialization[FST]
- Utility classes about primitives, collections, functional interfaces, concurrency, reflection, etc.

It was created to regroup and share classes, methods and dependencies between the different projects of the Atlanmod
team, and was designed to ease updating without interfering with other projects.

Some methods are inspired by https://github.com/google/guava[Guava].

== Latest release

The most recent release is Atlanmod Commons 1.1.0, released on May 21, 2021.
- Javadoc: https://atlanmod.github.io/Commons/releases/latest/doc/[commons]

To add a dependency on this library using Maven, use the following:

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.atlanmod.commons</groupId>
    <artifactId>commons-core</artifactId>
    <version>1.1.0</version>
  </dependency>

  <dependency>
    <groupId>org.atlanmod.commons</groupId>
    <artifactId>commons-testing</artifactId>
    <version>1.1.0</version>
  </dependency>
</dependencies>
----

== Snapshots

Snapshots are automatically build from the `master` and are available through Maven using `1.1.1-SNAPSHOT`.
- Javadoc: https://atlanmod.github.io/Commons/releases/snapshot/doc/[commons]

== SonarCloud badges

image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=alert_status[Quality Gate Status,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=bugs[Bugs,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=code_smells[Code Smells,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=coverage[Coverage,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=duplicated_lines_density[Duplicated Lines (%),link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=ncloc[Lines of Code,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=sqale_rating[Maintainability Rating,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=reliability_rating[Reliability Rating,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=security_rating[Security Rating,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]
image:https://sonarcloud.io/api/project_badges/measure?project=org.atlanmod.commons%3Acommons&metric=sqale_index[Technical Debt,link=https://sonarcloud.io/dashboard?id=org.atlanmod.commons%3Acommons]